### ISSUE TITLE
I/O board schematics

### ISSUE THREAD

**Issue by ghost** [Audio-Injector/Ultra#13]
I know that Audioinjector is not a open hardware project, but can you share schematics of I/O board?
I need to make Raspberry Pi shield with different form factor than you made.

**Comment by ghost** [comment]
I already found it in https://github.com/flatmax/AudioInjector.ultra.IO

Thanks!

**Comment by flatmax** [comment]
Thanks Arseniusz,
I have forked to AudioInjector as well :
https://github.com/Audio-Injector/AudioInjector.ultra.IO
