### ISSUE TITLE
Are these still availble to buy in the UK?

### ISSUE THREAD

**Issue by dodgyKnee73** [Audio-Injector/Ultra#32]

**Comment by flatmax** [comment]
Amazon UK have put in place difficult tax regulations - for that reason 
we aren't selling through Amazon UK. We are trying to find a way into 
Europe - however I am not sure if you can ship to the UK any more from 
the rest of Europe ?

Either way, your best bet right now is Ebay or our shop : 
https://shop.audioinjector.net/

There are two shipping choices on our shop, Express and Standard. 
Express is definitely the better option. However if you want to save 
money, choose standard shipping.

thanks

Matt
